In [79]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import metrics
import autosklearn.regression

AttributeError: module 'dask' has no attribute 'config'

In [2]:
df = pd.read_csv('../final_features.csv')

In [3]:
df.columns

Index(['Unnamed: 0', 'date', 'start_station_id', 'start_hour',
       'total_bike_trips', 'start_station_name', 'city', 'zip_code',
       'mean_temperature_f', 'mean_humidity', 'mean_visibility_miles',
       'mean_wind_speed_mph', 'precipitation_inches', 'weekday', 'isHoliday',
       'isRushHour', 'Hour 0', 'Hour 1', 'Hour 2', 'Hour 3', 'Hour 4',
       'Hour 5', 'Hour 6', 'Hour 7', 'Hour 8', 'Hour 9', 'Hour 10', 'Hour 11',
       'Hour 12', 'Hour 13', 'Hour 14', 'Hour 15', 'Hour 16', 'Hour 17',
       'Hour 18', 'Hour 19', 'Hour 20', 'Hour 21', 'Hour 22', 'Hour 23',
       'Station 3', 'Station 4', 'Station 5', 'Station 7', 'Station 8',
       'Station 14', 'Station 22', 'Station 27', 'Station 28', 'Station 30',
       'Station 32', 'Station 61', 'Station 64', 'Station 69', 'Station 70',
       'Station 83', 'Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday',
       'Tuesday', 'Wednesday', '94041', '94063', '94107', '95113'],
      dtype='object')

In [4]:
df.head()

Unnamed: 0        date  start_station_id  start_hour  total_bike_trips  \
0           0  2013-08-29                 3          13                 1   
1           1  2013-08-29                 3          18                 1   
2           2  2013-08-29                 3          20                 1   
3           3  2013-08-29                 3          21                 2   
4           4  2013-08-29                 3          22                 4   

      start_station_name      city  zip_code  mean_temperature_f  \
0  San Jose Civic Center  San Jose     95113                72.0   
1  San Jose Civic Center  San Jose     95113                72.0   
2  San Jose Civic Center  San Jose     95113                72.0   
3  San Jose Civic Center  San Jose     95113                72.0   
4  San Jose Civic Center  San Jose     95113                72.0   

   mean_humidity  ...    Monday  Saturday  Sunday Thursday  Tuesday  \
0           69.0  ...         0         0       0        1        0   
1           69.0  ...         0         0       0        1        0   
2           69.0  ...         0         0       0        1        0   
3           69.0  ...         0         0       0        1        0   
4           69.0  ...         0         0       0        1        0   

   Wednesday  94041  94063  94107  95113  
0          0      0      0      0      1  
1          0      0      0      0      1  
2          0      0      0      0      1  
3          0      0      0      0      1  
4          0      0      0      0      1  

[5 rows x 67 columns]

In [43]:
df_final = df.dropna()

def lin_reg(feature_cols, linreg):
    X = df_final[feature_cols]
    y = df_final["total_bike_trips"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    linreg.fit(X_train, y_train) # Fit model to training data
    y_pred_train = linreg.predict(X_train) # X_train predictions
    print("\ny_pred_train:")
    print(y_pred_train)
    y_pred_test = linreg.predict(X_test) # X_test predictions
    print("\ny_pred_test:")
    print(y_pred_test)
    # Demonstrates accuracy 
    # rounded_y_pred_test = np.rint(y_pred_test)
    # rounded_y_pred_train = np.rint(y_pred_train)
    diff_test = y_pred_test - y_test
    diff_train = y_pred_train - y_train
    accuracy_train = (len(diff_train) - np.count_nonzero(diff_train))/len(diff_train)
    accuracy_test = (len(diff_test) - np.count_nonzero(diff_test))/len(diff_test)
    print("\nTraining Accuracy:")
    print(accuracy_train)
    print("\nTest Accuracy:")
    print(accuracy_test)
    # Prints y-intercept 
    print("\ny-intercept:")
    print(linreg.intercept_)
    # Prints the beta coefficients in same order as passed
    print("\nCoefficients in same order as passed:")
    print(linreg.coef_)
    # Zip can pair feature names and coefficients together
    zip(feature_cols, linreg.coef_)
    
    print("\nTESTING ERRORS:")
    # prints result of MAE
    print("\nMAE:")
    print(metrics.mean_absolute_error(y_test, y_pred_test))
    # prints result of MSE
    print("\nMSE:")
    print(metrics.mean_squared_error(y_test, y_pred_test))
    # prtins result of RMSE 
    print("\nRMSE:")
    print(np.sqrt(metrics.mean_squared_error(y_test, y_pred_test)))
    print("\n\n\nTRAINING ERRORS:")
    # prints result of MAE
    print("\nMAE:")
    print(metrics.mean_absolute_error(y_train, y_pred_train))
    # prints result of MSE
    print("\nMSE:")
    print(metrics.mean_squared_error(y_train, y_pred_train))
    # prtins result of RMSE 
    print("\nRMSE:")
    print(np.sqrt(metrics.mean_squared_error(y_train, y_pred_train)))

In [44]:
feature_cols = ["mean_humidity", "mean_visibility_miles", "precipitation_inches"]

### Ordinary Least Squares Linear regression

In [48]:
lin_reg(feature_cols, LinearRegression())


y_pred_train:
[2.78369948 2.46038145 3.06390844 ... 2.82680855 3.02079937 2.9776903 ]

y_pred_test:
[2.69748134 2.82680855 2.86991762 ... 2.76214495 2.99924484 2.89147216]

Training Accuracy:
0.0

Test Accuracy:
0.0

y-intercept:
1.4053760152665538

Coefficients in same order as passed:
[ 0.02155454  0.00419423 -0.52917649]

TESTING ERRORS:

MAE:
2.2813227541147096

MSE:
16.71799784751501

RMSE:
4.08876483152492



TRAINING ERRORS:

MAE:
2.217584250564252

MSE:
15.086158017517587

RMSE:
3.884090371955522


## Ridge regression

In [46]:
lin_reg(feature_cols, Ridge(alpha=0.5))


y_pred_train:
[2.78369828 2.46039282 3.06389634 ... 2.82680567 3.02078894 2.97768155]

y_pred_test:
[2.69748349 2.82680567 2.86991306 ... 2.76214458 2.99923524 2.89146676]

Training Accuracy:
0.0

Test Accuracy:
0.0

y-intercept:
1.4052556959120246

Coefficients in same order as passed:
[ 0.0215537   0.00421134 -0.5286834 ]

TESTING ERRORS:

MAE:
2.281323018600895

MSE:
16.718001837219454

RMSE:
4.088765319411161



TRAINING ERRORS:

MAE:
2.2175838475819343

MSE:
15.086158021551057

RMSE:
3.884090372474752


In [69]:
feature_cols = ['start_hour', 'zip_code', 'mean_temperature_f',
       'mean_humidity', 'mean_visibility_miles', 'mean_wind_speed_mph',
       'precipitation_inches', 'isHoliday', 'isRushHour', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']
lin_reg(feature_cols, Ridge(alpha=0.5))


y_pred_train:
[2.01150666 4.40540379 4.65618152 ... 4.89576575 2.91226296 2.43174216]

y_pred_test:
[2.89836614 2.89540912 1.45499906 ... 1.01738142 3.60995993 3.61834522]

Training Accuracy:
0.0

Test Accuracy:
0.0

y-intercept:
140.55453859366716

Coefficients in same order as passed:
[-1.02638745e-01 -1.44775152e-03 -1.13599653e-02  2.79680806e-03
 -1.47051070e-01  1.36670186e-01 -1.42819620e+00 -4.84198911e-01
  1.87427004e+00  1.44035394e-01  3.51450115e-01 -7.61923843e-01
 -8.27719356e-01  3.34310697e-01  3.67116358e-01  3.92730634e-01]

TESTING ERRORS:

MAE:
2.153522197712843

MSE:
14.387339987929755

RMSE:
3.793064722349166



TRAINING ERRORS:

MAE:
2.0944236328803814

MSE:
13.038534627881498

RMSE:
3.6108911127146297


In [64]:
lin_reg(feature_cols, Lasso(alpha=0.01))


y_pred_train:
[1.96366579 4.32915353 4.53442533 ... 4.75893414 2.87133391 2.49536057]

y_pred_test:
[2.8816648  2.85299946 1.58612657 ... 1.11699    3.57057427 3.56647324]

Training Accuracy:
0.0

Test Accuracy:
0.0

y-intercept:
141.6759807089733

Coefficients in same order as passed:
[-1.02669143e-01 -1.46080017e-03 -9.81354610e-03  2.28278097e-03
 -1.06070251e-01  1.30076770e-01 -7.47911986e-01 -1.35412789e-01
  1.84359261e+00 -1.03473700e-01  0.00000000e+00 -9.52226069e-01
 -1.00187741e+00  0.00000000e+00  7.43028866e-04  2.68382370e-02]

TESTING ERRORS:

MAE:
2.1440083874060596

MSE:
14.416174831890858

RMSE:
3.7968638152942566



TRAINING ERRORS:

MAE:
2.085817529540443

MSE:
13.054288479559125

RMSE:
3.6130718896195693


In [70]:
feature_cols = ['start_hour', 'zip_code', 'isHoliday', 'isRushHour', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']
lin_reg(feature_cols, LinearRegression())


y_pred_train:
[1.9872484  3.64012672 3.92223096 ... 3.74968338 2.42545404 2.4239983 ]

y_pred_test:
[3.64012672 2.9046302  1.5160636  ... 0.77134423 3.84398934 3.84398934]

Training Accuracy:
0.0

Test Accuracy:
0.0

y-intercept:
157.99084247048356

Coefficients in same order as passed:
[-1.01931310e-01 -1.64302020e-03 -6.27698918e-01  1.82626054e+00
  1.74102015e-01  3.75948982e-01 -7.33832688e-01 -8.36483791e-01
  2.77489071e-01  3.87045725e-01  3.55730685e-01]

TESTING ERRORS:

MAE:
2.1680583729926837

MSE:
14.62659418121897

RMSE:
3.824473059287903



TRAINING ERRORS:

MAE:
2.1070608160489637

MSE:
13.245487632627313

RMSE:
3.639435070533243


In [73]:
lin_reg(feature_cols, Ridge(alpha=0.5))


y_pred_train:
[1.98716446 3.64005215 3.92215456 ... 3.74959391 2.42548466 2.4240362 ]

y_pred_test:
[3.64005215 2.90455397 1.51623862 ... 0.77143648 3.84391648 3.84391648]

Training Accuracy:
0.0

Test Accuracy:
0.0

y-intercept:
157.9917998907774

Coefficients in same order as passed:
[-1.01932167e-01 -1.64302951e-03 -6.27368800e-01  1.82616049e+00
  1.74068427e-01  3.75880496e-01 -7.33729156e-01 -8.36346764e-01
  2.77449053e-01  3.86990813e-01  3.55687131e-01]

TESTING ERRORS:

MAE:
2.1680465480160387

MSE:
14.626604473236828

RMSE:
3.8244744048348434



TRAINING ERRORS:

MAE:
2.1070494374333113

MSE:
13.245487642836862

RMSE:
3.6394350719358712


In [143]:
# Model that includes all feature columns 
feature_cols = ['start_station_id', 'mean_temperature_f', 'mean_humidity', 'mean_visibility_miles',
       'mean_wind_speed_mph', 'precipitation_inches', 'isHoliday',
       'isRushHour', 'Hour 0', 'Hour 1', 'Hour 2', 'Hour 3', 'Hour 4',
       'Hour 5', 'Hour 6', 'Hour 7', 'Hour 8', 'Hour 9', 'Hour 10', 'Hour 11',
       'Hour 12', 'Hour 13', 'Hour 14', 'Hour 15', 'Hour 16', 'Hour 17',
       'Hour 18', 'Hour 19', 'Hour 20', 'Hour 21', 'Hour 22', 'Hour 23',
       'Station 3', 'Station 4', 'Station 5', 'Station 7', 'Station 8',
       'Station 14', 'Station 22', 'Station 27', 'Station 28', 'Station 30',
       'Station 32', 'Station 61', 'Station 64', 'Station 69', 'Station 70',
       'Station 83', 'Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday',
       'Tuesday', 'Wednesday', '94041', '94063', '94107', '95113']
lin_reg(feature_cols)


y_pred_train:
[2.04246273 6.04439856 5.53422438 ... 4.87165945 2.42120807 4.40350941]

y_pred_test:
[3.88869007 4.06255679 0.54804536 ... 0.16310152 4.30191956 3.95205618]

Training Accuracy:
0.18781144572719677

Test Accuracy:
0.18398894055548573

y-intercept:
-2.1469376745463884

Coefficients in same order as passed:
[ 0.00832089  0.02402521  0.00739357  0.02005234 -0.02345736 -0.81076202
 -0.68047552  2.01449136 -0.63342169  0.71609851 -0.09784174 -0.53351545
 -0.91910557 -0.11050199  0.26241301  0.61952945  3.28968721  1.40218048
 -1.55481118  0.11122695  0.28663086  0.21443271  0.08037082  0.23171127
 -0.81324774  0.36402685 -0.09574606 -1.19712765 -0.2811876  -0.45018922
 -0.38169063 -0.50992159  0.22462277 -0.19497768 -0.1140814  -0.09817234
 -0.20213348  0.45382306  0.17043448 -0.01375224  0.21653996 -0.54107017
 -0.1999333  -0.21238957 -0.8415554   0.67391748  2.01502162 -1.33629379
  0.15534606  0.43216224 -0.87677381 -0.82747637  0.30747453  0.42884183
  0.38042553 -0.53821